version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/practice/src
    ports:
      - 3000:3000

  practiceDB:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'practicedb'
      MYSQL_ROOT_PASSWORD: 'root'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
